[DEFAULT]
verbose = True
debug = True

[universal_agent]
uuid5_name = s3aas
payload_path = /var/lib/exordos/exordos_metapaas/payload.json
orch_endpoint = http://metapaas-cp.local.genesis-core.tech:11011
status_endpoint = http://metapaas-cp.local.genesis-core.tech:11012
caps_drivers = S3CapabilityDriver
